spring:
    profiles:
        active:
        -dev
        
---

server:
  port: 8001
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.vow.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

spring:
  application:
    profiles: dev
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app-name: miceoservicecloudDept8001
  company.name: vow
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

---

server:
  port: 8001
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.vow.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

spring:
  application:
    profiles: test
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app-name: miceoservicecloudDept8001
  company.name: vow
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

